POST http://localhost:8080/auth/realms/fincycle/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=nest
&client_secret=dcfdc03d-4436-4849-963f-159ba331d725
&grant_type=password
&username=user1@user.com
&password=123456